<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="StudentDetail.Dashboard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
   <title>Student Details</title>
   <link href="Style.css" rel="stylesheet"></link>
   <script src="Scripts/jquery-1.6.4.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">
        $(function () {
            var stud = $.connection.studentHub;
            // Define the function recieveData which was declared in StudentHub
            stud.client.recieveData = function (studentDataCollection) {
                var $tbl = $('#tblJobInfo');
                if (studentDataCollection.length > 0) {
                    $tbl.empty();
                    $tbl.append(' <tr><th>Id</th><th>First Name</th><th>Last Name</th><th>Mark 1</th><th>Mark 2</th><th>Mark 3</th><th>Total</th><th>Average</th></tr>');
                    var rows = [];
                    for (var i = 0; i < studentDataCollection.length; i++) {
                        rows.push(' <tr><td>' + studentDataCollection[i].Id + '</td><td>' + studentDataCollection[i].FirstName + '</td><td>' + studentDataCollection[i].LastName + '</td><td>' + studentDataCollection[i].Mark1 + '</td><td>' + studentDataCollection[i].Mark2 + '</td><td>' + studentDataCollection[i].Mark3 + '</td><td>' + studentDataCollection[i].Total + '</td><td>' + studentDataCollection[i].Average + '</td></tr>');
                    }
                    $tbl.append(rows.join(''));
                }
            };
            $.connection.hub.start().done(function () {
                stud.server.sendData();
            });
        });

    </script>
</head>
<body>
     <div id="main"> 
         <h1>Student details using Signal R !!!</h1> 
        <table id="tblJobInfo">
        </table>
    </div>
    <%-- <asp:GridView ID="grdStudentDetails" runat="server" AutoGenerateColumns="False" Width="646px">
        <Columns>
            <asp:BoundField AccessibleHeaderText="Id" DataField="Id" HeaderText="Id" />
            <asp:BoundField AccessibleHeaderText="First Name" DataField="FirstName" HeaderText="First Name" />
            <asp:BoundField AccessibleHeaderText="Last Name" DataField="LastName" HeaderText="Last Name" />
            <asp:BoundField AccessibleHeaderText="Mark 1" DataField="Mark1" HeaderText="Mark 1" />
            <asp:BoundField AccessibleHeaderText="Mark 2" DataField="Mark2" HeaderText="Mark 2" />
            <asp:BoundField AccessibleHeaderText="Mark 3" DataField="Mark3" HeaderText="Mark 3" />
            <asp:BoundField AccessibleHeaderText="Total" DataField="Total" HeaderText="Total" />
            <asp:BoundField AccessibleHeaderText="Average" DataField="Average" HeaderText="Average" />
        </Columns>
    </asp:GridView>--%>
</body>
  
</html>
